"""secdns — a small, zero-dependency authoritative DNS server for the SecRouter suite.

Serves an internal zone (generated by SecDeploy from the site topology) so components on
different hosts resolve each other by name, and forwards everything else upstream (or refuses,
on a closed network). Standard library only.
"""

from __future__ import annotations

__version__ = "0.1.0"

from .config import Config
from .resolver import Resolver
from .zone import Zone

__all__ = ["Config", "Resolver", "Zone", "__version__"]
